# _config.yml
title: "Octant Monitor"
baseurl: "/monitor_test"  # Replace with your repository name
url: ""  # Replace with your GitHub Pages URL if you have a custom domain

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - .gitignore

# Include files
include:
  - _layouts
  - _includes
  - assets
  - styles.css
  - script.js